gw/force-app/main/default/objects/Contract_Data__c/Contract_Data__c.object-meta.xml
<CustomObject>
    <label>Contract Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Contract_Data__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract_Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gw/force-app/main/default/objects/Contract_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract_Datas</relationshipLabel>
    <relationshipName>Contract_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

gw/force-app/main/default/objects/External_Data__c/External_Data__c.object-meta.xml
<CustomObject>
    <label>External Data</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>External_Data__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gw/force-app/main/default/classes/ContractData.cls
public with sharing class ContractData {
    @AuraEnabled(cacheable=true)
    public static List<Contract_Data__c> getCdList(string accountid) {
        return [
            SELECT Id, Name, Review_Date__c
            FROM Contract_Data__c
            WHERE Account__c = :accountId
        ];
    }
    @AuraEnabled(cacheable=true)
    public static List<External_Data__c> getexDsList(string accountid) {
        return [
            SELECT Id, Name
            FROM External_Data__c
            WHERE Account__c = :accountId
        ];
    }
}